### ISSUE TITLE
Crash while processing the game folder

### ISSUE THREAD

**Issue by wczhou5697** [MiMLoader/MiMLoader#4]
The copy function failed due to copying the loader itself into game folder at firstTime.ts in lines 16.
After I replicate the script behavior by myself, it works fine.

Also, if the loader would stop when it crashed that would be helpful for gathering the error message instead of just exit the program immediately.

Operating System: Window 11

**Comment by AhhhSaturn** [comment]
heya! ive made a new release that should save exceptions to a log file for now but if you have errors i would recommend running the program through the shell as it wont exit from there and give error info.
would you be able to pop the error youre getting in here because i font have a windows machine to test on right now and the error doesnt seem to be happening on linux.

**Comment by wczhou5697** [comment]
I am glad to hear that.
And here is the error log
```
D:\SteamLibrary\steamapps\common\Moonstone Island>Moonstone.Island.Mod.Loader.exe
Starting MiMLoader
[0.89ms] Started Copying original game files
2 | var UU=Object.create;var{defineProperty:k7,getPrototypeOf:HU,getOwnPropertyNames:PU}=Object;var AU=Object.prototype.hasOwnProperty;var w4=(X,Y,Z)=>{Z=X!=null?UU(HU(X)):{};const Q=Y||!X||!X.__esModule?k7(Z,"default",{value:X,enumerable:!0}):Z;for(let $ of PU(X))if(!AU.call(Q,$))k7(Q,$,{get:()=>X[$],enumerable:!0});return Q};var j=(X,Y)=>()=>(Y||X((Y={exports:{}}).exports,Y),Y.exports);var T8=(X,Y)=>{for(var Z in Y)k7(X,Z,{get:Y[Z],enumerable:!0,configurable:!0,set:(Q)=>Y[Z]=()=>Q})};var Y0=j((_U)=>{_U.fromCallback=function(X){return Object.defineProperty(function(...Y){if(typeof Y[Y.length-1]==="function")X.apply(this,Y);else return new Promise((Z,Q)=>{Y.push(($,J)=>$!=null?Q($):Z(J)),X.apply(this,Y)})},"name",{value:X.name})};_U.fromPromise=function(X){return Object.defineProperty(function(...Y){const Z=Y[Y.length-1];if(typeof Z!=="function")return X.apply(this,Y);else Y.pop(),X.apply(this,Y).then((Q)=>Z(null,Q),Z)},"name",{value:X.name})}});var gQ=j((RE,kQ)=>{var BU=function(X){if(U8.hasOwnProperty("O_SYMLIN | ... truncated

error: Cannot copy 'D:\SteamLibrary\steamapps\common\Moonstone Island' to a subdirectory of itself, 'D:\SteamLibrary\steamapps\common\Moonstone Island\game'.
      at B:/~BUN/root/Moonstone.Island.Mod.Loader.exe:2:16087

Bun v1.1.18 (Windows x64)
```

**Comment by AhhhSaturn** [comment]
you have run the launcher from inside the original game, make a new folder in the steam common folder and run the exe from there :D

**Comment by wczhou5697** [comment]
Yeah that make a lot of sense now, since I found that fs-extra do not allow you to copy into the subdirectory.
But the readme said run the installer inside the original game folder, that might need to change

**Comment by AhhhSaturn** [comment]
ah yeah shit sorry, I've been meaning to update but get carried away with the code
